# Generated by Django 5.1.4 on 2024-12-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0002_mesero_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesero',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='mesero',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='mesero',
            name='procedencia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
